"""Geometry utilities used by grasp retargeting stages."""

from .mano_surface import (
    ManoSurfaceSamples,
    ManoSurfaceTopology,
    materialize_mano_surface_samples,
    sample_mano_surface,
    sample_mano_surface_topology,
    write_mano_surface_samples_html,
)
from .contact_clustering import (
    ContactCluster,
    ManoObjectContactResult,
    extract_mano_object_contact_clusters,
    radius_connected_components,
)
from .contact_mapping import (
    ContactMappingResult,
    diverse_soft_surface_mapping,
    link_soft_surface_mapping,
    mapping_result_to_json_dict,
    nearest_surface_mapping,
    run_all_contact_mapping_schemes,
    soft_surface_mapping,
)
from .contact_retargeting import (
    CandidateForceClosureScore,
    ContactPatchTarget,
    ManoToRobotFrameMapping,
    RetargetCandidate,
    RetargetOptimizationConfig,
    RetargetOptimizationResult,
    assign_patches_to_robot_surface,
    build_contact_patch_targets,
    build_hand_frame,
    canonicalize_patch_targets,
    map_canonical_mano_patches_to_robot_frame,
    materialize_assigned_robot_contacts,
    optimize_retarget_action,
    rank_candidates_by_strict_force_closure,
    retarget_loss_terms,
    robot_tip_from_link,
)
from .mano_shadow_initialization import (
    ManoShadowInitialization,
    action_summary,
    mano_pose_to_shadow_action,
)
from .robot_surface import (
    MjcfRobotSurfaceModel,
    RobotSurfaceSamples,
    RobotSurfaceTopology,
    UrdfRobotSurfaceModel,
    load_robot_surface_model,
)
from .surface_sampling import (
    MeshSurfaceSamples,
    MeshSurfaceTopology,
    materialize_mesh_surface_samples,
    sample_mesh_surface,
    sample_mesh_surface_topology,
)

__all__ = [
    "ContactCluster",
    "ContactMappingResult",
    "ContactPatchTarget",
    "CandidateForceClosureScore",
    "ManoObjectContactResult",
    "ManoShadowInitialization",
    "ManoSurfaceSamples",
    "ManoSurfaceTopology",
    "ManoToRobotFrameMapping",
    "MeshSurfaceSamples",
    "MeshSurfaceTopology",
    "MjcfRobotSurfaceModel",
    "RetargetCandidate",
    "RetargetOptimizationConfig",
    "RetargetOptimizationResult",
    "RobotSurfaceSamples",
    "RobotSurfaceTopology",
    "UrdfRobotSurfaceModel",
    "assign_patches_to_robot_surface",
    "build_contact_patch_targets",
    "build_hand_frame",
    "canonicalize_patch_targets",
    "diverse_soft_surface_mapping",
    "extract_mano_object_contact_clusters",
    "link_soft_surface_mapping",
    "load_robot_surface_model",
    "action_summary",
    "mapping_result_to_json_dict",
    "map_canonical_mano_patches_to_robot_frame",
    "mano_pose_to_shadow_action",
    "materialize_assigned_robot_contacts",
    "materialize_mesh_surface_samples",
    "materialize_mano_surface_samples",
    "nearest_surface_mapping",
    "optimize_retarget_action",
    "rank_candidates_by_strict_force_closure",
    "radius_connected_components",
    "retarget_loss_terms",
    "robot_tip_from_link",
    "run_all_contact_mapping_schemes",
    "sample_mesh_surface",
    "sample_mesh_surface_topology",
    "sample_mano_surface",
    "sample_mano_surface_topology",
    "soft_surface_mapping",
    "write_mano_surface_samples_html",
]
